projects:
- app_name: coin
  app_path: coin
  app_run: true
  app_bin: true
  app_fmt: true
  app_watcher:
    paths:
    - /
    ignore_paths:
    - vendor
    exts:
    - .go
    output:
      cli: true
      file: false
- app_name: echo
  app_path: echo
  app_run: true
  app_bin: true
  app_fmt: true
  app_watcher:
    paths:
    - /
    ignore_paths:
    - vendor
    exts:
    - .go
    output:
      cli: true
      file: false
- app_name: loop
  app_path: loop
  app_run: true
  app_bin: true
  app_fmt: true
  app_watcher:
    paths:
    - /
    ignore_paths:
    - vendor
    exts:
    - .go
    output:
      cli: true
      file: false
- app_name: printer
  app_path: print/printer
  app_run: true
  app_bin: true
  app_fmt: true
  app_watcher:
    paths:
    - /
    ignore_paths:
    - vendor
    exts:
    - .go
    output:
      cli: true
      file: true
- app_name: server
  app_path: server
  app_run: true
  app_bin: true
  app_fmt: true
  app_watcher:
    paths:
    - /
    ignore_paths:
    - vendor
    exts:
    - .go
    output:
      cli: true
      file: false
- app_name: args
  app_path: args
  app_run: true
  app_bin: true
  app_fmt: true
  app_params:
  - test
  app_watcher:
    paths:
    - /
    ignore_paths:
    - vendor
    exts:
    - .go
    output:
      cli: true
      file: false
