version: v1.0
projects:
- app_name: print
  app_path: print/printer
  app_run: true
  app_bin: true
  app_fmt: true
  app_watcher:
    paths:
    - /
    ignore_paths:
    - vendor
    - bin
    exts:
    - .go
- app_name: coin
  app_path: coin
  app_run: true
  app_bin: true
  app_fmt: true
  app_watcher:
    paths:
    - /
    ignore_paths:
    - vendor
    - bin
    exts:
    - .go
- app_name: server
  app_path: server
  app_run: true
  app_bin: true
  app_fmt: true
  app_watcher:
    paths:
    - /
    ignore_paths:
    - vendor
    - bin
    exts:
    - .go
- app_name: echo
  app_path: echo
  app_run: true
  app_bin: true
  app_fmt: true
  app_watcher:
    paths:
    - /
    ignore_paths:
    - vendor
    - bin
    exts:
    - .go
